"""empty message

Revision ID: 181c11e4d2da
Revises: 65414cea89d8
Create Date: 2021-04-05 15:33:46.459345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181c11e4d2da'
down_revision = '65414cea89d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres_venue', sa.ARRAY(sa.String()), nullable=False))
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('Venue', 'genres_venue')
    # ### end Alembic commands ###
