"""empty message

Revision ID: 3652066a5b9f
Revises: c9abd7d4f8ed
Create Date: 2021-03-29 22:04:47.817267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3652066a5b9f'
down_revision = 'c9abd7d4f8ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Show', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Show', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Show', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Show', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
