"""empty message

Revision ID: 51194db4432f
Revises: 181c11e4d2da
Create Date: 2021-04-05 15:34:48.266050

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '51194db4432f'
down_revision = '181c11e4d2da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.ARRAY(sa.String()), nullable=False))
    op.drop_column('Artist', 'genres_artist')
    op.add_column('Venue', sa.Column('genres', sa.ARRAY(sa.String()), nullable=False))
    op.drop_column('Venue', 'genres_venue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres_venue', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_column('Venue', 'genres')
    op.add_column('Artist', sa.Column('genres_artist', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###
