"""empty message

Revision ID: e49676fdea00
Revises: 51194db4432f
Create Date: 2021-04-09 14:48:37.744478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e49676fdea00'
down_revision = '51194db4432f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Album', sa.Column('name', sa.String(length=120), nullable=True))
    op.drop_column('Album', 'title')
    op.add_column('Song', sa.Column('title', sa.String(length=120), nullable=True))
    op.drop_column('Song', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Song', sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Song', 'title')
    op.add_column('Album', sa.Column('title', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Album', 'name')
    # ### end Alembic commands ###
